version: "3.8"
services:
  superserver:
    image: svtishkevich777/server:latest
    networks:
      - beltelecom
    ports:
    - target: 8080
      published: 81
  superclient:
    image: svtishkevich777/client:latest
    networks:
      - beltelecom
    ports:
    - target: 8080
      published: 82
networks:
  beltelecom:
